;;; Compiled snippets and support files for `coq-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'coq-mode
                     '(("wlog" "wlog : / $1\n" "wlog" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/wlog" nil nil)
                       ("wilog" "without loss $1\n" "without loss" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/without_loss" nil nil)
                       ("vmc" "vm_compute.\n" "vm_compute" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/vm_compute" nil nil)
                       ("varv" "Variant $1 : $2 := $3 : $4.\n" "Variant" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/variant" nil nil)
                       ("vs" "Variables $1 , $2: $3.\n" "Variables" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/variables" nil nil)
                       ("v" "Variable $1: $2.\n" "Variable" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/variable" nil nil)
                       ("unset_verbose_compat_notations" "Unset Verbose Compat Notations\n" "Unset Verbose Compat Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_verbose_compat_notations" nil nil)
                       ("unset_universe_polymorphism" "Unset Universe Polymorphism\n" "Unset Universe Polymorphism" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_universe_polymorphism" nil nil)
                       ("unset_universe_minimization_tounset" "Unset Universe Minimization ToUnset\n" "Unset Universe Minimization ToUnset" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_universe_minimization_tounset" nil nil)
                       ("unset_universal_lemma_under_conjunction" "Unset Universal Lemma Under Conjunction\n" "Unset Universal Lemma Under Conjunction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_universal_lemma_under_conjunction" nil nil)
                       ("unset_undo" "Unset Undo\n" "Unset Undo" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_undo" nil nil)
                       ("unset_typeclasses_unique_solutions" "Unset Typeclasses Unique Solutions\n" "Unset Typeclasses Unique Solutions" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_unique_solutions" nil nil)
                       ("unset_typeclasses_unique_instances" "Unset Typeclasses Unique Instances\n" "Unset Typeclasses Unique Instances" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_unique_instances" nil nil)
                       ("unset_typeclasses_strict_resolution" "Unset Typeclasses Strict Resolution\n" "Unset Typeclasses Strict Resolution" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_strict_resolution" nil nil)
                       ("unset_typeclasses_modulo_eta" "Unset Typeclasses Modulo Eta\n" "Unset Typeclasses Modulo Eta" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_modulo_eta" nil nil)
                       ("unset_typeclasses_depth" "Unset Typeclasses Depth\n" "Unset Typeclasses Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_depth" nil nil)
                       ("unset_typeclasses_dependency_order" "Unset Typeclasses Dependency Order\n" "Unset Typeclasses Dependency Order" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_dependency_order" nil nil)
                       ("unset_typeclasses_debug" "Unset Typeclasses Debug\n" "Unset Typeclasses Debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclasses_debug" nil nil)
                       ("unset_typeclass_resolution_for_conversion" "Unset Typeclass Resolution For Conversion\n" "Unset Typeclass Resolution For Conversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclass_resolution_for_conversion" nil nil)
                       ("unset_typeclass_resolution_after_apply" "Unset Typeclass Resolution After Apply\n" "Unset Typeclass Resolution After Apply" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_typeclass_resolution_after_apply" nil nil)
                       ("unset_transparent_obligations" "Unset Transparent Obligations\n" "Unset Transparent Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_transparent_obligations" nil nil)
                       ("unset_tactic_pattern_unification" "Unset Tactic Pattern Unification\n" "Unset Tactic Pattern Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_tactic_pattern_unification" nil nil)
                       ("unset_tactic_evars_pattern_unification" "Unset Tactic Evars Pattern Unification\n" "Unset Tactic Evars Pattern Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_tactic_evars_pattern_unification" nil nil)
                       ("unset_tactic_compat_context" "Unset Tactic Compat Context\n" "Unset Tactic Compat Context" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_tactic_compat_context" nil nil)
                       ("unset_suggest_proof_using" "Unset Suggest Proof Using\n" "Unset Suggest Proof Using" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_suggest_proof_using" nil nil)
                       ("unset_strongly_strict_implicit" "Unset Strongly Strict Implicit\n" "Unset Strongly Strict Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_strongly_strict_implicit" nil nil)
                       ("unset_strict_universe_declaration" "Unset Strict Universe Declaration\n" "Unset Strict Universe Declaration" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_strict_universe_declaration" nil nil)
                       ("unset_strict_proofs" "Unset Strict Proofs\n" "Unset Strict Proofs" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_strict_proofs" nil nil)
                       ("unset_standard_proposition_elimination_names" "Unset Standard Proposition Elimination Names\n" "Unset Standard Proposition Elimination Names" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_standard_proposition_elimination_names" nil nil)
                       ("unset_simpliscbn" "Unset SimplIsCbn\n" "Unset SimplIsCbn" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_simpliscbn" nil nil)
                       ("unset_silent" "Unset Silent\n" "Unset Silent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_silent" nil nil)
                       ("unset_shrink_obligations" "Unset Shrink Obligations\n" "Unset Shrink Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_shrink_obligations" nil nil)
                       ("unset_short_module_printing" "Unset Short Module Printing\n" "Unset Short Module Printing" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_short_module_printing" nil nil)
                       ("unset_search_blacklist" "Unset Search Blacklist\n" "Unset Search Blacklist" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_search_blacklist" nil nil)
                       ("unset_rewriting_schemes" "Unset Rewriting Schemes\n" "Unset Rewriting Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_rewriting_schemes" nil nil)
                       ("unset_reversible_pattern_implicit" "Unset Reversible Pattern Implicit\n" "Unset Reversible Pattern Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_reversible_pattern_implicit" nil nil)
                       ("unset_regular_subst_tactic" "Unset Regular Subst Tactic\n" "Unset Regular Subst Tactic" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_regular_subst_tactic" nil nil)
                       ("unset_refine_instance_mode" "Unset Refine Instance Mode\n" "Unset Refine Instance Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_refine_instance_mode" nil nil)
                       ("unset_record_elimination_schemes" "Unset Record Elimination Schemes\n" "Unset Record Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_record_elimination_schemes" nil nil)
                       ("unset_proof_using_clear_unused" "Unset Proof Using Clear Unused\n" "Unset Proof Using Clear Unused" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_proof_using_clear_unused" nil nil)
                       ("unset_program_mode" "Unset Program Mode\n" "Unset Program Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_program_mode" nil nil)
                       ("unset_printing_wildcard" "Unset Printing Wildcard\n" "Unset Printing Wildcard" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_wildcard" nil nil)
                       ("unset_printing_width" "Unset Printing Width\n" "Unset Printing Width" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_width" nil nil)
                       ("unset_printing_universes" "Unset Printing Universes\n" "Unset Printing Universes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_universes" nil nil)
                       ("unset_printing_synth" "Unset Printing Synth\n" "Unset Printing Synth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_synth" nil nil)
                       ("unset_printing_records" "Unset Printing Records\n" "Unset Printing Records" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_records" nil nil)
                       ("unset_printing_record" "Unset Printing Record\n" "Unset Printing Record" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_record" nil nil)
                       ("unset_printing_projections" "Unset Printing Projections\n" "Unset Printing Projections" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_projections" nil nil)
                       ("unset_printing_primitive_projection_parameters" "Unset Printing Primitive Projection Parameters\n" "Unset Printing Primitive Projection Parameters" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_primitive_projection_parameters" nil nil)
                       ("unset_printing_primitive_projection_compatibility" "Unset Printing Primitive Projection Compatibility\n" "Unset Printing Primitive Projection Compatibility" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_primitive_projection_compatibility" nil nil)
                       ("unset_printing_notations" "Unset Printing Notations\n" "Unset Printing Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_notations" nil nil)
                       ("unset_printing_matching" "Unset Printing Matching\n" "Unset Printing Matching" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_matching" nil nil)
                       ("unset_printing_let" "Unset Printing Let\n" "Unset Printing Let" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_let" nil nil)
                       ("unset_printing_implicit_defensive" "Unset Printing Implicit Defensive\n" "Unset Printing Implicit Defensive" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_implicit_defensive" nil nil)
                       ("unset_printing_implicit" "Unset Printing Implicit\n" "Unset Printing Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_implicit" nil nil)
                       ("unset_printing_if" "Unset Printing If\n" "Unset Printing If" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_if" nil nil)
                       ("unset_printing_existential_instances" "Unset Printing Existential Instances\n" "Unset Printing Existential Instances" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_existential_instances" nil nil)
                       ("unset_printing_depth" "Unset Printing Depth\n" "Unset Printing Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_depth" nil nil)
                       ("unset_printing_constructor" "Unset Printing Constructor\n" "Unset Printing Constructor" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_constructor" nil nil)
                       ("unset_printing_coercions" "Unset Printing Coercions\n" "Unset Printing Coercions" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_coercions" nil nil)
                       ("unset_printing_coercion" "Unset Printing Coercion\n" "Unset Printing Coercion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_coercion" nil nil)
                       ("unset_printing_all" "Unset Printing All\n" "Unset Printing All" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_printing_all" nil nil)
                       ("unset_primitive_projections" "Unset Primitive Projections\n" "Unset Primitive Projections" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_primitive_projections" nil nil)
                       ("unset_parsing_explicit" "Unset Parsing Explicit\n" "Unset Parsing Explicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_parsing_explicit" nil nil)
                       ("unset_nonrecursive_elimination_schemes" "Unset Nonrecursive Elimination Schemes\n" "Unset Nonrecursive Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_nonrecursive_elimination_schemes" nil nil)
                       ("unset_maximal_implicit_insertion" "Unset Maximal Implicit Insertion\n" "Unset Maximal Implicit Insertion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_maximal_implicit_insertion" nil nil)
                       ("unset_ltac_debug" "Unset Ltac Debug\n" "Unset Ltac Debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_ltac_debug" nil nil)
                       ("unset_loose_hint_behavior" "Unset Loose Hint Behavior\n" "Unset Loose Hint Behavior" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_loose_hint_behavior" nil nil)
                       ("unset_keyed_unification" "Unset Keyed Unification\n" "Unset Keyed Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_keyed_unification" nil nil)
                       ("unset_kernel_term_sharing" "Unset Kernel Term Sharing\n" "Unset Kernel Term Sharing" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_kernel_term_sharing" nil nil)
                       ("unset_intuition_negation_unfolding" "Unset Intuition Negation Unfolding\n" "Unset Intuition Negation Unfolding" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_intuition_negation_unfolding" nil nil)
                       ("unset_intuition_iff_unfolding" "Unset Intuition Iff Unfolding\n" "Unset Intuition Iff Unfolding" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_intuition_iff_unfolding" nil nil)
                       ("unset_inline_level" "Unset Inline Level\n" "Unset Inline Level" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_inline_level" nil nil)
                       ("unset_injection_on_proofs" "Unset Injection On Proofs\n" "Unset Injection On Proofs" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_injection_on_proofs" nil nil)
                       ("unset_injection_l2r_pattern_order" "Unset Injection L2R Pattern Order\n" "Unset Injection L2R Pattern Order" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_injection_l2r_pattern_order" nil nil)
                       ("unset_info_trivial" "Unset Info Trivial\n" "Unset Info Trivial" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_info_trivial" nil nil)
                       ("unset_info_level" "Unset Info Level\n" "Unset Info Level" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_info_level" nil nil)
                       ("unset_info_eauto" "Unset Info Eauto\n" "Unset Info Eauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_info_eauto" nil nil)
                       ("unset_info_auto" "Unset Info Auto\n" "Unset Info Auto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_info_auto" nil nil)
                       ("unset_implicit_arguments" "Unset Implicit Arguments\n" "Unset Implicit Arguments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_implicit_arguments" nil nil)
                       ("unset_hyps_limit" "Unset Hyps Limit\n" "Unset Hyps Limit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_hyps_limit" nil nil)
                       ("unset_hide_obligations" "Unset Hide Obligations\n" "Unset Hide Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_hide_obligations" nil nil)
                       ("unset_functional_induction_rewrite_dependent" "Unset Functional Induction Rewrite Dependent\n" "Unset Functional Induction Rewrite Dependent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_functional_induction_rewrite_dependent" nil nil)
                       ("unset_function_raw_tcc" "Unset Function_raw_tcc\n" "Unset Function_raw_tcc" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_function_raw_tcc" nil nil)
                       ("unset_function_debug" "Unset Function_debug\n" "Unset Function_debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_function_debug" nil nil)
                       ("unset_firstorder_depth" "Unset Firstorder Depth\n" "Unset Firstorder Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_firstorder_depth" nil nil)
                       ("unset_extraction_typeexpand" "Unset Extraction TypeExpand\n" "Unset Extraction TypeExpand" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_typeexpand" nil nil)
                       ("unset_extraction_safeimplicits" "Unset Extraction SafeImplicits\n" "Unset Extraction SafeImplicits" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_safeimplicits" nil nil)
                       ("unset_extraction_optimize" "Unset Extraction Optimize\n" "Unset Extraction Optimize" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_optimize" nil nil)
                       ("unset_extraction_keepsingleton" "Unset Extraction KeepSingleton\n" "Unset Extraction KeepSingleton" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_keepsingleton" nil nil)
                       ("unset_extraction_flag" "Unset Extraction Flag\n" "Unset Extraction Flag" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_flag" nil nil)
                       ("unset_extraction_file_comment" "Unset Extraction File Comment\n" "Unset Extraction File Comment" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_file_comment" nil nil)
                       ("unset_extraction_conservative_types" "Unset Extraction Conservative Types\n" "Unset Extraction Conservative Types" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_conservative_types" nil nil)
                       ("unset_extraction_autoinline" "Unset Extraction AutoInline\n" "Unset Extraction AutoInline" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_autoinline" nil nil)
                       ("unset_extraction_accessopaque" "Unset Extraction AccessOpaque\n" "Unset Extraction AccessOpaque" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_extraction_accessopaque" nil nil)
                       ("unset_equality_scheme" "Unset Equality Scheme\n" "Unset Equality Scheme" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_equality_scheme" nil nil)
                       ("unset_elimination_schemes" "Unset Elimination Schemes\n" "Unset Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_elimination_schemes" nil nil)
                       ("unset_dump_bytecode" "Unset Dump Bytecode\n" "Unset Dump Bytecode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_dump_bytecode" nil nil)
                       ("unset_discriminate_introduction" "Unset Discriminate Introduction\n" "Unset Discriminate Introduction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_discriminate_introduction" nil nil)
                       ("unset_dependent_propositions_elimination" "Unset Dependent Propositions Elimination\n" "Unset Dependent Propositions Elimination" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_dependent_propositions_elimination" nil nil)
                       ("unset_default_timeout" "Unset Default Timeout\n" "Unset Default Timeout" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_default_timeout" nil nil)
                       ("unset_default_proof_using" "Unset Default Proof Using\n" "Unset Default Proof Using" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_default_proof_using" nil nil)
                       ("unset_default_proof_mode" "Unset Default Proof Mode\n" "Unset Default Proof Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_default_proof_mode" nil nil)
                       ("unset_default_goal_selector" "Unset Default Goal Selector\n" "Unset Default Goal Selector" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_default_goal_selector" nil nil)
                       ("unset_default_clearing_used_hypotheses" "Unset Default Clearing Used Hypotheses\n" "Unset Default Clearing Used Hypotheses" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_default_clearing_used_hypotheses" nil nil)
                       ("unset_decidable_equality_schemes" "Unset Decidable Equality Schemes\n" "Unset Decidable Equality Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_decidable_equality_schemes" nil nil)
                       ("unset_debug_unification" "Unset Debug Unification\n" "Unset Debug Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_unification" nil nil)
                       ("unset_debug_trivial" "Unset Debug Trivial\n" "Unset Debug Trivial" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_trivial" nil nil)
                       ("unset_debug_tactic_unification" "Unset Debug Tactic Unification\n" "Unset Debug Tactic Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_tactic_unification" nil nil)
                       ("unset_debug_rakam" "Unset Debug RAKAM\n" "Unset Debug RAKAM" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_rakam" nil nil)
                       ("unset_debug_eauto" "Unset Debug Eauto\n" "Unset Debug Eauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_eauto" nil nil)
                       ("unset_debug_auto" "Unset Debug Auto\n" "Unset Debug Auto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_debug_auto" nil nil)
                       ("unset_contextual_implicit" "Unset Contextual Implicit\n" "Unset Contextual Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_contextual_implicit" nil nil)
                       ("unset_congruence_verbose" "Unset Congruence Verbose\n" "Unset Congruence Verbose" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_congruence_verbose" nil nil)
                       ("unset_congruence_depth" "Unset Congruence Depth\n" "Unset Congruence Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_congruence_depth" nil nil)
                       ("unset_compat_notations" "Unset Compat Notations\n" "Unset Compat Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_compat_notations" nil nil)
                       ("unset_case_analysis_schemes" "Unset Case Analysis Schemes\n" "Unset Case Analysis Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_case_analysis_schemes" nil nil)
                       ("unset_bullet_behavior" "Unset Bullet Behavior\n" "Unset Bullet Behavior" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_bullet_behavior" nil nil)
                       ("unset_bracketing_last_introduction_pattern" "Unset Bracketing Last Introduction Pattern\n" "Unset Bracketing Last Introduction Pattern" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_bracketing_last_introduction_pattern" nil nil)
                       ("unset_boolean_equality_schemes" "Unset Boolean Equality Schemes\n" "Unset Boolean Equality Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_boolean_equality_schemes" nil nil)
                       ("unset_automatic_introduction" "Unset Automatic Introduction\n" "Unset Automatic Introduction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_automatic_introduction" nil nil)
                       ("unset_automatic_coercions_import" "Unset Automatic Coercions Import\n" "Unset Automatic Coercions Import" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_automatic_coercions_import" nil nil)
                       ("unset_atomic_load" "Unset Atomic Load\n" "Unset Atomic Load" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_atomic_load" nil nil)
                       ("unset_asymmetric_patterns" "Unset Asymmetric Patterns\n" "Unset Asymmetric Patterns" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unset_asymmetric_patterns" nil nil)
                       ("unlock" "unlock $1\n" "unlock" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unlock" nil nil)
                       ("u" "unfold $1\n" "unfold" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unfold" nil nil)
                       ("unfocus" "Unfocus.\n" "Unfocus" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/unfocus" nil nil)
                       ("typeclasses_opaque" "Typeclasses Opaque $1.\n" "Typeclasses Opaque" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/typeclasses_opaque" nil nil)
                       ("tryif" "tryif $1 then $2 else $3\n" "tryif" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/tryif" nil nil)
                       ("try" "try $1\n" "try" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/try" nil nil)
                       ("t" "trivial\n" "trivial" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/trivial" nil nil)
                       ("transparent" "Transparent $1.\n" "Transparent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/transparent" nil nil)
                       ("trans" "transitivity $1\n" "transitivity" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/transitivity" nil nil)
                       ("timeout" "Timeout\n" "Timeout" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/timeout" nil nil)
                       ("th" "Theorem $1 : $2.\n$3\nQed.\n" "Theorem" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/theorem" nil nil)
                       ("ta" "tauto\n" "tauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/tauto" nil nil)
                       ("tactic_notation" "Tactic Notation $1 := $2.\n" "Tactic Notation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/tactic_notation" nil nil)
                       ("sy" "symmetry\n" "symmetry" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/symmetry" nil nil)
                       ("suffices" "suffices $1 : $2\n" "suffices" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/suffices" nil nil)
                       ("suff" "suff $1 : $2\n" "suff" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/suff" nil nil)
                       ("su" "subst $1\n" "subst" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/subst" nil nil)
                       ("str" "Structure $1 : $2 := {\n$3 : $4;\n$5 : $6 }\n" "Structure" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/structure" nil nil)
                       ("strategy" "Strategy $1 [$2].\n" "Strategy" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/strategy" nil nil)
                       ("str" "stepr $1\n" "stepr" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/stepr" nil nil)
                       ("stl" "stepl $1\n" "stepl" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/stepl" nil nil)
                       ("sprm" "splitRmult\n" "split_Rmult" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/split_rmult" nil nil)
                       ("spra" "splitRabs\n" "split_Rabs" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/split_rabs" nil nil)
                       ("sp" "split\n" "split" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/split" nil nil)
                       ("spec" "specialize\n" "specialize" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/specialize" nil nil)
                       ("oblssolve" "Solve Obligations using $1.\n" "Solve Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/solve_obligations" nil nil)
                       ("solve" "solve [ $1 | $2 ]\n" "solve" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/solve" nil nil)
                       ("simeq" "simplify_eq ${1:hyp}\n" "simplify_eq" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/simplify_eq" nil nil)
                       ("sinv" "simple inversion\n" "simple inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/simple_inversion" nil nil)
                       ("sind" "simple induction\n" "simple induction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/simple_induction" nil nil)
                       ("sdes" "simple destruct\n" "simple destruct" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/simple_destruct" nil nil)
                       ("s" "simpl\n" "simpl" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/simpl" nil nil)
                       ("show" "Show $1.\n" "Show" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/show" nil nil)
                       ("strew" "setoid rewrite $1\n" "setoid rewrite" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/setoid_rewrite" nil nil)
                       ("strep" "setoid replace $1 with $2\n" "setoid replace with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/setoid_replace_with" nil nil)
                       ("set_verbose_compat_notations" "Set Verbose Compat Notations\n" "Set Verbose Compat Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_verbose_compat_notations" nil nil)
                       ("set_universe_polymorphism" "Set Universe Polymorphism\n" "Set Universe Polymorphism" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_universe_polymorphism" nil nil)
                       ("set_universe_minimization_toset" "Set Universe Minimization ToSet\n" "Set Universe Minimization ToSet" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_universe_minimization_toset" nil nil)
                       ("set_universal_lemma_under_conjunction" "Set Universal Lemma Under Conjunction\n" "Set Universal Lemma Under Conjunction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_universal_lemma_under_conjunction" nil nil)
                       ("set_undo" "Set Undo\n" "Set Undo" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_undo" nil nil)
                       ("set_typeclasses_unique_solutions" "Set Typeclasses Unique Solutions\n" "Set Typeclasses Unique Solutions" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_unique_solutions" nil nil)
                       ("set_typeclasses_unique_instances" "Set Typeclasses Unique Instances\n" "Set Typeclasses Unique Instances" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_unique_instances" nil nil)
                       ("set_typeclasses_strict_resolution" "Set Typeclasses Strict Resolution\n" "Set Typeclasses Strict Resolution" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_strict_resolution" nil nil)
                       ("set_typeclasses_modulo_eta" "Set Typeclasses Modulo Eta\n" "Set Typeclasses Modulo Eta" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_modulo_eta" nil nil)
                       ("set_typeclasses_depth" "Set Typeclasses Depth\n" "Set Typeclasses Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_depth" nil nil)
                       ("set_typeclasses_dependency_order" "Set Typeclasses Dependency Order\n" "Set Typeclasses Dependency Order" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_dependency_order" nil nil)
                       ("set_typeclasses_debug" "Set Typeclasses Debug\n" "Set Typeclasses Debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclasses_debug" nil nil)
                       ("set_typeclass_resolution_for_conversion" "Set Typeclass Resolution For Conversion\n" "Set Typeclass Resolution For Conversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclass_resolution_for_conversion" nil nil)
                       ("set_typeclass_resolution_after_apply" "Set Typeclass Resolution After Apply\n" "Set Typeclass Resolution After Apply" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_typeclass_resolution_after_apply" nil nil)
                       ("set_transparent_obligations" "Set Transparent Obligations\n" "Set Transparent Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_transparent_obligations" nil nil)
                       ("set_tactic_pattern_unification" "Set Tactic Pattern Unification\n" "Set Tactic Pattern Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_tactic_pattern_unification" nil nil)
                       ("set_tactic_evars_pattern_unification" "Set Tactic Evars Pattern Unification\n" "Set Tactic Evars Pattern Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_tactic_evars_pattern_unification" nil nil)
                       ("set_tactic_compat_context" "Set Tactic Compat Context\n" "Set Tactic Compat Context" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_tactic_compat_context" nil nil)
                       ("set_suggest_proof_using" "Set Suggest Proof Using\n" "Set Suggest Proof Using" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_suggest_proof_using" nil nil)
                       ("set_strongly_strict_implicit" "Set Strongly Strict Implicit\n" "Set Strongly Strict Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_strongly_strict_implicit" nil nil)
                       ("set_strict_universe_declaration" "Set Strict Universe Declaration\n" "Set Strict Universe Declaration" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_strict_universe_declaration" nil nil)
                       ("set_strict_proofs" "Set Strict Proofs\n" "Set Strict Proofs" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_strict_proofs" nil nil)
                       ("set_standard_proposition_elimination_names" "Set Standard Proposition Elimination Names\n" "Set Standard Proposition Elimination Names" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_standard_proposition_elimination_names" nil nil)
                       ("set_simpliscbn" "Set SimplIsCbn\n" "Set SimplIsCbn" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_simpliscbn" nil nil)
                       ("set_silent" "Set Silent\n" "Set Silent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_silent" nil nil)
                       ("set_shrink_obligations" "Set Shrink Obligations\n" "Set Shrink Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_shrink_obligations" nil nil)
                       ("set_short_module_printing" "Set Short Module Printing\n" "Set Short Module Printing" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_short_module_printing" nil nil)
                       ("set_search_blacklist" "Set Search Blacklist\n" "Set Search Blacklist" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_search_blacklist" nil nil)
                       ("set_rewriting_schemes" "Set Rewriting Schemes\n" "Set Rewriting Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_rewriting_schemes" nil nil)
                       ("set_reversible_pattern_implicit" "Set Reversible Pattern Implicit\n" "Set Reversible Pattern Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_reversible_pattern_implicit" nil nil)
                       ("set_regular_subst_tactic" "Set Regular Subst Tactic\n" "Set Regular Subst Tactic" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_regular_subst_tactic" nil nil)
                       ("set_refine_instance_mode" "Set Refine Instance Mode\n" "Set Refine Instance Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_refine_instance_mode" nil nil)
                       ("set_record_elimination_schemes" "Set Record Elimination Schemes\n" "Set Record Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_record_elimination_schemes" nil nil)
                       ("set_proof_using_clear_unused" "Set Proof Using Clear Unused\n" "Set Proof Using Clear Unused" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_proof_using_clear_unused" nil nil)
                       ("set_program_mode" "Set Program Mode\n" "Set Program Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_program_mode" nil nil)
                       ("set_printing_wildcard" "Set Printing Wildcard\n" "Set Printing Wildcard" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_wildcard" nil nil)
                       ("set_printing_width" "Set Printing Width\n" "Set Printing Width" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_width" nil nil)
                       ("set_printing_universes" "Set Printing Universes\n" "Set Printing Universes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_universes" nil nil)
                       ("set_printing_unfocused" "Set Printing Unfocused\n" "Set Printing Unfocused" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_unfocused" nil nil)
                       ("set_printing_synth" "Set Printing Synth\n" "Set Printing Synth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_synth" nil nil)
                       ("set_printing_records" "Set Printing Records\n" "Set Printing Records" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_records" nil nil)
                       ("set_printing_record" "Set Printing Record\n" "Set Printing Record" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_record" nil nil)
                       ("set_printing_projections" "Set Printing Projections\n" "Set Printing Projections" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_projections" nil nil)
                       ("set_printing_primitive_projection_parameters" "Set Printing Primitive Projection Parameters\n" "Set Printing Primitive Projection Parameters" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_primitive_projection_parameters" nil nil)
                       ("set_printing_primitive_projection_compatibility" "Set Printing Primitive Projection Compatibility\n" "Set Printing Primitive Projection Compatibility" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_primitive_projection_compatibility" nil nil)
                       ("set_printing_notations" "Set Printing Notations\n" "Set Printing Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_notations" nil nil)
                       ("set_printing_matching" "Set Printing Matching\n" "Set Printing Matching" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_matching" nil nil)
                       ("set_printing_let" "Set Printing Let\n" "Set Printing Let" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_let" nil nil)
                       ("set_printing_implicit_defensive" "Set Printing Implicit Defensive\n" "Set Printing Implicit Defensive" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_implicit_defensive" nil nil)
                       ("set_printing_implicit" "Set Printing Implicit\n" "Set Printing Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_implicit" nil nil)
                       ("set_printing_if" "Set Printing If\n" "Set Printing If" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_if" nil nil)
                       ("set_printing_goal_tags" "Set Printing Goal Tags\n" "Set Printing Goal Tags" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_goal_tags" nil nil)
                       ("set_printing_goal_names" "Set Printing Goal Names\n" "Set Printing Goal Names" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_goal_names" nil nil)
                       ("set_printing_existential_instances" "Set Printing Existential Instances\n" "Set Printing Existential Instances" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_existential_instances" nil nil)
                       ("set_printing_depth" "Set Printing Depth\n" "Set Printing Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_depth" nil nil)
                       ("set_printing_constructor" "Set Printing Constructor\n" "Set Printing Constructor" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_constructor" nil nil)
                       ("set_printing_compact_contexts" "Set Printing Compact Contexts\n" "Set Printing Compact Contexts" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_compact_contexts" nil nil)
                       ("set_printing_coercions" "Set Printing Coercions\n" "Set Printing Coercions" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_coercions" nil nil)
                       ("set_printing_coercion" "Set Printing Coercion\n" "Set Printing Coercion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_coercion" nil nil)
                       ("set_printing_all" "Set Printing All\n" "Set Printing All" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_printing_all" nil nil)
                       ("set_primitive_projections" "Set Primitive Projections\n" "Set Primitive Projections" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_primitive_projections" nil nil)
                       ("set_parsing_explicit" "Set Parsing Explicit\n" "Set Parsing Explicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_parsing_explicit" nil nil)
                       ("set_nonrecursive_elimination_schemes" "Set Nonrecursive Elimination Schemes\n" "Set Nonrecursive Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_nonrecursive_elimination_schemes" nil nil)
                       ("set_maximal_implicit_insertion" "Set Maximal Implicit Insertion\n" "Set Maximal Implicit Insertion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_maximal_implicit_insertion" nil nil)
                       ("set_ltac_debug" "Set Ltac Debug\n" "Set Ltac Debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_ltac_debug" nil nil)
                       ("set_loose_hint_behavior" "Set Loose Hint Behavior\n" "Set Loose Hint Behavior" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_loose_hint_behavior" nil nil)
                       ("set_keyed_unification" "Set Keyed Unification\n" "Set Keyed Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_keyed_unification" nil nil)
                       ("set_kernel_term_sharing" "Set Kernel Term Sharing\n" "Set Kernel Term Sharing" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_kernel_term_sharing" nil nil)
                       ("set_intuition_negation_unfolding" "Set Intuition Negation Unfolding\n" "Set Intuition Negation Unfolding" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_intuition_negation_unfolding" nil nil)
                       ("set_intuition_iff_unfolding" "Set Intuition Iff Unfolding\n" "Set Intuition Iff Unfolding" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_intuition_iff_unfolding" nil nil)
                       ("set_inline_level" "Set Inline Level\n" "Set Inline Level" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_inline_level" nil nil)
                       ("set_injection_on_proofs" "Set Injection On Proofs\n" "Set Injection On Proofs" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_injection_on_proofs" nil nil)
                       ("set_injection_l2r_pattern_order" "Set Injection L2R Pattern Order\n" "Set Injection L2R Pattern Order" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_injection_l2r_pattern_order" nil nil)
                       ("set_info_trivial" "Set Info Trivial\n" "Set Info Trivial" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_info_trivial" nil nil)
                       ("set_info_level" "Set Info Level\n" "Set Info Level" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_info_level" nil nil)
                       ("set_info_eauto" "Set Info Eauto\n" "Set Info Eauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_info_eauto" nil nil)
                       ("set_info_auto" "Set Info Auto\n" "Set Info Auto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_info_auto" nil nil)
                       ("set_implicit_arguments" "Set Implicit Arguments\n" "Set Implicit Arguments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_implicit_arguments" nil nil)
                       ("set_hyps_limit" "Set Hyps Limit\n" "Set Hyps Limit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_hyps_limit" nil nil)
                       ("set_hide_obligations" "Set Hide Obligations\n" "Set Hide Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_hide_obligations" nil nil)
                       ("set_functional_induction_rewrite_dependent" "Set Functional Induction Rewrite Dependent\n" "Set Functional Induction Rewrite Dependent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_functional_induction_rewrite_dependent" nil nil)
                       ("set_function_raw_tcc" "Set Function_raw_tcc\n" "Set Function_raw_tcc" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_function_raw_tcc" nil nil)
                       ("set_function_debug" "Set Function_debug\n" "Set Function_debug" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_function_debug" nil nil)
                       ("set_firstorder_depth" "Set Firstorder Depth\n" "Set Firstorder Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_firstorder_depth" nil nil)
                       ("set_extraction_typeexpand" "Set Extraction TypeExpand\n" "Set Extraction TypeExpand" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_typeexpand" nil nil)
                       ("set_extraction_safeimplicits" "Set Extraction SafeImplicits\n" "Set Extraction SafeImplicits" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_safeimplicits" nil nil)
                       ("set_extraction_optimize" "Set Extraction Optimize\n" "Set Extraction Optimize" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_optimize" nil nil)
                       ("set_extraction_keepsingleton" "Set Extraction KeepSingleton\n" "Set Extraction KeepSingleton" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_keepsingleton" nil nil)
                       ("set_extraction_flag" "Set Extraction Flag\n" "Set Extraction Flag" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_flag" nil nil)
                       ("set_extraction_file_comment" "Set Extraction File Comment\n" "Set Extraction File Comment" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_file_comment" nil nil)
                       ("set_extraction_conservative_types" "Set Extraction Conservative Types\n" "Set Extraction Conservative Types" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_conservative_types" nil nil)
                       ("set_extraction_autoinline" "Set Extraction AutoInline\n" "Set Extraction AutoInline" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_autoinline" nil nil)
                       ("set_extraction_accessopaque" "Set Extraction AccessOpaque\n" "Set Extraction AccessOpaque" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_extraction_accessopaque" nil nil)
                       ("set_equality_scheme" "Set Equality Scheme\n" "Set Equality Scheme" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_equality_scheme" nil nil)
                       ("set_elimination_schemes" "Set Elimination Schemes\n" "Set Elimination Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_elimination_schemes" nil nil)
                       ("set_dump_bytecode" "Set Dump Bytecode\n" "Set Dump Bytecode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_dump_bytecode" nil nil)
                       ("set_discriminate_introduction" "Set Discriminate Introduction\n" "Set Discriminate Introduction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_discriminate_introduction" nil nil)
                       ("set_dependent_propositions_elimination" "Set Dependent Propositions Elimination\n" "Set Dependent Propositions Elimination" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_dependent_propositions_elimination" nil nil)
                       ("set_default_timeout" "Set Default Timeout\n" "Set Default Timeout" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_default_timeout" nil nil)
                       ("set_default_proof_using" "Set Default Proof Using\n" "Set Default Proof Using" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_default_proof_using" nil nil)
                       ("set_default_proof_mode" "Set Default Proof Mode\n" "Set Default Proof Mode" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_default_proof_mode" nil nil)
                       ("set_default_goal_selector" "Set Default Goal Selector\n" "Set Default Goal Selector" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_default_goal_selector" nil nil)
                       ("set_default_clearing_used_hypotheses" "Set Default Clearing Used Hypotheses\n" "Set Default Clearing Used Hypotheses" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_default_clearing_used_hypotheses" nil nil)
                       ("set_decidable_equality_schemes" "Set Decidable Equality Schemes\n" "Set Decidable Equality Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_decidable_equality_schemes" nil nil)
                       ("set_debug_unification" "Set Debug Unification\n" "Set Debug Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_unification" nil nil)
                       ("set_debug_trivial" "Set Debug Trivial\n" "Set Debug Trivial" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_trivial" nil nil)
                       ("set_debug_tactic_unification" "Set Debug Tactic Unification\n" "Set Debug Tactic Unification" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_tactic_unification" nil nil)
                       ("set_debug_rakam" "Set Debug RAKAM\n" "Set Debug RAKAM" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_rakam" nil nil)
                       ("set_debug_eauto" "Set Debug Eauto\n" "Set Debug Eauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_eauto" nil nil)
                       ("set_debug_auto" "Set Debug Auto\n" "Set Debug Auto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_debug_auto" nil nil)
                       ("set_contextual_implicit" "Set Contextual Implicit\n" "Set Contextual Implicit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_contextual_implicit" nil nil)
                       ("set_congruence_verbose" "Set Congruence Verbose\n" "Set Congruence Verbose" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_congruence_verbose" nil nil)
                       ("set_congruence_depth" "Set Congruence Depth\n" "Set Congruence Depth" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_congruence_depth" nil nil)
                       ("set_compat_notations" "Set Compat Notations\n" "Set Compat Notations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_compat_notations" nil nil)
                       ("set_case_analysis_schemes" "Set Case Analysis Schemes\n" "Set Case Analysis Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_case_analysis_schemes" nil nil)
                       ("set_bullet_behavior" "Set Bullet Behavior\n" "Set Bullet Behavior" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_bullet_behavior" nil nil)
                       ("set_bracketing_last_introduction_pattern" "Set Bracketing Last Introduction Pattern\n" "Set Bracketing Last Introduction Pattern" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_bracketing_last_introduction_pattern" nil nil)
                       ("set_boolean_equality_schemes" "Set Boolean Equality Schemes\n" "Set Boolean Equality Schemes" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_boolean_equality_schemes" nil nil)
                       ("set_automatic_introduction" "Set Automatic Introduction\n" "Set Automatic Introduction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_automatic_introduction" nil nil)
                       ("set_automatic_coercions_import" "Set Automatic Coercions Import\n" "Set Automatic Coercions Import" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_automatic_coercions_import" nil nil)
                       ("set_atomic_load" "Set Atomic Load\n" "Set Atomic Load" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_atomic_load" nil nil)
                       ("set_asymmetric_patterns" "Set Asymmetric Patterns\n" "Set Asymmetric Patterns" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set_asymmetric_patterns" nil nil)
                       ("set" "set $1 := $2\n" "set" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/set" nil nil)
                       ("sec" "Section $1.\n" "Section" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/section" nil nil)
                       ("searchrewrite" "SearchRewrite $1\n" "SearchRewrite" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/searchrewrite" nil nil)
                       ("searchpattern" "SearchPattern ($1)\n" "SearchPattern" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/searchpattern" nil nil)
                       ("searchabout" "SearchAbout $1\n" "SearchAbout" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/searchabout" nil nil)
                       ("search" "Search $1\n" "Search" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/search" nil nil)
                       ("sc" "Scheme ${1:name} := $1.\n" "Scheme" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/scheme" nil nil)
                       ("save" "Save.\n" "Save" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/save" nil nil)
                       ("romega" "romega\n" "romega" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/romega" nil nil)
                       ("ring" "ring $1\n" "ring" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/ring" nil nil)
                       ("rig" "right\n" "right" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/right" nil nil)
                       ("rewrite_all" "rewrite_all\n" "rewrite_all <-" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/rewrite_all" nil nil)
                       ("r" "rewrite $1\n" "rewrite" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/rewrite" nil nil)
                       ("r" "revert dependent\n" "revert dependent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/revert_dependent" nil nil)
                       ("r" "revert\n" "revert" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/revert" nil nil)
                       ("reset_extraction_inline" "Reset Extraction Inline.\n" "Reset Extraction Inline" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/reset_extraction_inline" nil nil)
                       ("reserved_notation" "Reserved Notation\n" "Reserved Notation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/reserved_notation" nil nil)
                       ("reserved_infix" "Reserved Infix\n" "Reserved Infix" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/reserved_infix" nil nil)
                       ("require_import" "Require Import $1.\n" "Require Import" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/require_import" nil nil)
                       ("require_export" "Require Export $1.\n" "Require Export" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/require_export" nil nil)
                       ("require" "Require $1.\n" "Require" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/require" nil nil)
                       ("rep" "replace $1 with $2\n" "replace with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/replace_with" nil nil)
                       ("repeat" "repeat $1\n" "repeat" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/repeat" nil nil)
                       ("ren" "rename $1 into $2\n" "rename into" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/rename_into" nil nil)
                       ("remove_printing_let" "Remove Printing Let $1.\n" "Remove Printing Let" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/remove_printing_let" nil nil)
                       ("remove_printing_if" "Remove Printing If $1.\n" "Remove Printing If" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/remove_printing_if" nil nil)
                       ("remove_loadpath" "Remove LoadPath\n" "Remove LoadPath" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/remove_loadpath" nil nil)
                       ("rk" "Remark $1 : $2.\n$3\nQed.\n" "Remark" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/remark" nil nil)
                       ("refl" "reflexivity $1\n" "reflexivity" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/reflexivity" nil nil)
                       ("ref" "refine\n" "refine" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/refine" nil nil)
                       ("red" "red\n" "red" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/red" nil nil)
                       ("recextrm" "Recursive Extraction Module ${1:id}.\n" "Recursive Extraction Module" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/recursive_extraction_module" nil nil)
                       ("recextrl" "Recursive Extraction Library ${1:id}.\n" "Recursive Extraction Library" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/recursive_extraction_library" nil nil)
                       ("recextr" "Recursive Extraction ${1:id}.\n" "Recursive Extraction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/recursive_extraction" nil nil)
                       ("rec" "Record $1 : $2 := {\n$3 : $4;\n$5 : $6 }\n" "Record" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/record" nil nil)
                       ("quote" "quote\n" "quote" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/quote" nil nil)
                       ("qed" "Qed.\n" "Qed" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/qed" nil nil)
                       ("pwd" "Pwd.\n" "Pwd" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/pwd" nil nil)
                       ("psatz" "psatz\n" "psatz" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/psatz" nil nil)
                       ("pr" "Proposition $1 : $2.\nProof.\n$3\nQed.\n" "Proposition" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/proposition" nil nil)
                       ("prcongr" "prop_congr\n" "prop_congr" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/prop_congr" nil nil)
                       ("prol" "prolog\n" "prolog" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/prolog" nil nil)
                       ("progress" "progress $1\n" "progress" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/progress" nil nil)
                       ("pth" "Program Theorem $1 : $2.\nProof.\n$3\nQed.\n" "Program Theorem" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/program_theorem" nil nil)
                       ("pl" "Program Lemma $1 : $2.\nProof.\n$3\nQed.\n" "Program Lemma" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/program_lemma" nil nil)
                       ("pinstance" "Program Instance [ $1 ] => $2 where \n$3 := $4;\n$5 := $6.\n" "Program Instance" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/program_instance" nil nil)
                       ("pfix" "Program Fixpoint $1 ($2:$3) {struct ${1:arg}} : $4 :=\n$5.\n" "Program Fixpoint" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/program_fixpoint" nil nil)
                       ("pdef" "Program Definition $1:$2 := $3.\n" "Program Definition" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/program_definition" nil nil)
                       ("print_coercions" "Print Coercions.\n" "Print Coercions" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/print_coercions" nil nil)
                       ("p" "Print $1.\n" "Print" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/print" nil nil)
                       ("preterm" "Preterm.\n" "Preterm" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/preterm" nil nil)
                       ("pi" "Prenex Implicits $1\n" "Prenex Implicits" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/prenex_implicits" nil nil)
                       ("po" "pose $1 := $2\n" "pose" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/pose" nil nil)
                       ("pat" "pattern\n" "pattern" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/pattern" nil nil)
                       ("par" "Parameters $1: $2\n" "Parameters" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/parameters" nil nil)
                       ("par" "Parameter $1: $2\n" "Parameter" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/parameter" nil nil)
                       ("opsc" "Open Scope $1\n" "Open Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/open_scope" nil nil)
                       ("open_local_scope" "Open Local Scope $1\n" "Open Local Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/open_local_scope" nil nil)
                       ("opaque" "Opaque $1.\n" "Opaque" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/opaque" nil nil)
                       ("o" "omega\n" "omega" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/omega" nil nil)
                       ("obls" "Obligations $1.\n$2\nQed.\n" "Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/obligations" nil nil)
                       ("obligation_tactic" "Obligation Tactic := $1.\n" "Obligation Tactic" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/obligation_tactic" nil nil)
                       ("obl" "Obligation $1.\n$2\nQed.\n" "Obligation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/obligation" nil nil)
                       ("nsatz" "nsatz\n" "nsatz" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/nsatz" nil nil)
                       ("nra" "nra\n" "nra" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/nra" nil nil)
                       ("now_show" "now_show\n" "now_show" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/now_show" nil nil)
                       ("now" "now\n" "now" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/now" nil nil)
                       ("nots" "Notation $1 := $2.\n" "Notation (simple)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/notation_simple" nil nil)
                       ("nia" "nia\n" "nia" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/nia" nil nil)
                       ("nobl" "Next Obligation.\n$1\nQed.\n" "Next Obligation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/next_obligation" nil nil)
                       ("nnorm" "nat_norm\n" "nat_norm" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/nat_norm" nil nil)
                       ("ncongr" "nat_congr\n" "nat_congr" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/nat_congr" nil nil)
                       ("m" "multimatch $1 with\n| $2 => $3\nend\n" "multimatch with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/multimatch_with" nil nil)
                       ("mov" "move $1 after $2\n" "move after" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/move_after" nil nil)
                       ("m" "move\n" "move" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/move" nil nil)
                       ("mti" "Module Type $1.\n$2\nEnd $3.\n" "Module Type" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/module_type" nil nil)
                       ("moi" "Module $1 : $2.\n$3\nEnd $4.\n" "Module :" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/module" nil nil)
                       ("m5" "match $1 with\n| $2 => $3\n| $4 => $5\n| $6 => $7\n| $8 => $9\n| $10 => $11\nend\n" "match with 5" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/match_with_5" nil nil)
                       ("m4" "match $1 with\n| $2 => $3\n| $4 => $5\n| $6 => $7\n| $8 => $9\nend\n" "match with 4" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/match_with_4" nil nil)
                       ("m3" "match $1 with\n| $2 => $3\n| $4 => $5\n| $6 => $7\nend\n" "match with 3" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/match_with_3" nil nil)
                       ("m2" "match $1 with\n| $2 => $3\n| $4 => $5\nend\n" "match with 2" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/match_with_2" nil nil)
                       ("m" "match $1 with\n| $2 => $3\nend\n" "match with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/match_with" nil nil)
                       ("ltac" "Ltac $1 := $2\n" "Ltac" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/ltac" nil nil)
                       ("lra" "lra\n" "lra" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lra" nil nil)
                       ("locate_notation" "Locate Notation ($1) $2\n" "Locate Notation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/locate_notation" nil nil)
                       ("locate_library" "Locate Library $1.\n" "Locate Library" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/locate_library" nil nil)
                       ("locate" "Locate\n" "Locate" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/locate" nil nil)
                       ("local_strategy" "Local Strategy $1 [$2].\n" "Local Strategy" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_strategy" nil nil)
                       ("local_open_scope" "Local Open Scope $1\n" "Local Open Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_open_scope" nil nil)
                       ("lnots" "Local Notation $1 := $2.\n" "Local Notation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_notation" nil nil)
                       ("local_ltac" "Local Ltac $1 := $2\n" "Local Ltac" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_ltac" nil nil)
                       ("local_definition" "Local Definition $1:$2 := $3.\n" "Local Definition" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_definition" nil nil)
                       ("local_coercion" "Local Coercion ${1:id} : ${2:typ1} >-> ${3:typ2}.\n" "Local Coercion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_coercion" nil nil)
                       ("lclsc" "Local Close Scope $1\n" "Local Close Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_close_scope" nil nil)
                       ("local_axioms" "Local Axioms $1 , $2: $3\n" "Local Axioms" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_axioms" nil nil)
                       ("local_axiom" "Local Axiom $1 : $2\n" "Local Axiom" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_axiom" nil nil)
                       ("local_arguments" "Local Arguments ${1:id} : ${2:rule}\n" "Local Arguments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/local_arguments" nil nil)
                       ("load" "load\n" "load" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/load" nil nil)
                       ("lin" "linear\n" "linear" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/linear" nil nil)
                       ("lia" "lia\n" "lia" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lia" nil nil)
                       ("li" "let $1 := $2 in $3\n" "let in" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/let_in" nil nil)
                       ("Let" "Let $1 : $2 := $3.\n" "Let" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/let" nil nil)
                       ("l" "Lemma $1 : $2.\nProof.\n$3\nQed.\n" "Lemma" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lemma" nil nil)
                       ("left" "left\n" "left" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/left" nil nil)
                       ("m" "lazymatch $1 with\n| $2 => $3\nend\n" "lazymatch with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lazymatch_with" nil nil)
                       ("lazy" "lazy beta delta [$1] iota zeta\n" "lazy" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lazy" nil nil)
                       ("lst" "nil\n" "last" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/last" nil nil)
                       ("lap" "lapply\n" "lapply" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/lapply" nil nil)
                       ("invcl" "inversion_clear\n" "inversion_clear" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/inversion_clear" nil nil)
                       ("inv" "inversion $1\n" "inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/inversion" nil nil)
                       ("intu" "intuition $1\n" "intuition" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/intuition" nil nil)
                       ("is" "intros $1\n" "intros" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/intros" nil nil)
                       ("i" "intro\n" "intro" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/intro" nil nil)
                       ("inst" "instantiate\n" "instantiate" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/instantiate" nil nil)
                       ("instance" "Instance $1:$2.\nProof.\n$3Defined.\n" "Instance" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/instance" nil nil)
                       ("inspect" "Inspect $1.\n" "Inspect" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/inspect" nil nil)
                       ("inj" "injection $1\n" "injection" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/injection" nil nil)
                       ("info" "info $1\n" "info" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/info" nil nil)
                       ("indv" "Inductive $1 : $2 := $3 : $4.\n" "Inductive" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/inductive" nil nil)
                       ("ind" "induction $1\n" "induction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/induction" nil nil)
                       ("include" "Include $1.\n" "Include" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/include" nil nil)
                       ("import" "Import $1.\n" "Import" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/import" nil nil)
                       ("implicit_types" "Implicit Types $1 : $2.\n" "Implicit Types" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/implicit_types" nil nil)
                       ("implicit_arguments_on" "Implicit Arguments On.\n" "Implicit Arguments On" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/implicit_arguments_on" nil nil)
                       ("implicit_arguments_off" "Implicit Arguments Off.\n" "Implicit Arguments Off" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/implicit_arguments_off" nil nil)
                       ("implicit_arguments" "Implicit Arguments $1 [$2].\n" "Implicit Arguments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/implicit_arguments" nil nil)
                       ("if" "if $1 then $2 else $3\n" "if" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/if" nil nil)
                       ("idtac" "idtac\n" "idtac" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/idtac" nil nil)
                       ("identity_coercion" "Identity Coercion $1.\n" "Identity Coercion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/identity_coercion" nil nil)
                       ("hyp" "Hypothesis $1: $2\n" "Hypothesis" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hypothesis" nil nil)
                       ("hyp" "Hypotheses $1: $2\n" "Hypotheses" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hypotheses" nil nil)
                       ("hnf" "hnf\n" "hnf" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hnf" nil nil)
                       ("hv" "Hint View for $1\n" "Hint View for" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_view_for" nil nil)
                       ("hu" "Hint Unfold $1 : $2.\n" "Hint Unfold" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_unfold" nil nil)
                       ("hrw" "Hint Rewrite -> ${1:t1,t2...} using ${2:tac} : ${3:db}.\n" "Hint Rewrite ->" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_rewrite" nil nil)
                       ("hr" "Hint Resolve $1 : ${1:db}.\n" "Hint Resolve" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_resolve" nil nil)
                       ("hi" "Hint Immediate $1 : ${1:db}.\n" "Hint Immediate" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_immediate" nil nil)
                       ("he" "Hint Extern ${1:cost} ${2:pat} => ${3:tac} : ${4:db}.\n" "Hint Extern" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_extern" nil nil)
                       ("hc" "Hint Constructors $1 : $2.\n" "Hint Constructors" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/hint_constructors" nil nil)
                       ("hv" "have $1 : $2\n" "have" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/have" nil nil)
                       ("goal" "Goal $1.\n" "Goal" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/goal" nil nil)
                       ("gvs" "Global Variables $1 , $2: $3.\n" "Global Variables" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/global_variables" nil nil)
                       ("gv" "Global Variable $1: $2.\n" "Global Variable" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/global_variable" nil nil)
                       ("gfa" "gfail\n" "gfail" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/gfail" nil nil)
                       ("gd" "generalize dependent $1\n" "generalize dependent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/generalize_dependent" nil nil)
                       ("g" "generalize $1\n" "generalize" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/generalize" nil nil)
                       ("generalizable_variables" "Generalizable Variables $1.\n" "Generalizable Variables" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/generalizable_variables" nil nil)
                       ("generalizable_all_variables" "Generalizable All Variables.\n" "Generalizable All Variables" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/generalizable_all_variables" nil nil)
                       ("fs" "Functional Scheme ${1:name} := Induction for ${2:fun}.\n" "Functional Scheme" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/functional_scheme" nil nil)
                       ("finv" "functional inversion ${1:H}\n" "functional inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/functional_inversion" nil nil)
                       ("fi" "functional induction ${1:f} ${2:args}\n" "functional induction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/functional_induction" nil nil)
                       ("func" "Function $1 ($2:$3) {struct ${1:arg}} : $4 :=\n$5.\n" "Function" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/function" nil nil)
                       ("f4" "fun ($1:$2) ($3:$4) ($5:$6) ($7:$8) => $9\n" "fun (4 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fun_4_args" nil nil)
                       ("f3" "fun ($1:$2) ($3:$4) ($5:$6) => $7\n" "fun (3 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fun_3_args" nil nil)
                       ("f2" "fun ($1:$2) ($3:$4) => $5\n" "fun (2 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fun_2_args" nil nil)
                       ("f" "fun $1:$2 => $3\n" "fun (1 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fun_1_args" nil nil)
                       ("four" "fourier\n" "fourier" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fourier" nil nil)
                       ("fo4" "forall ($1:$2) ($3:$4) ($5:$6) ($7:$8), $9\n" "forall (4 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/forall_4_args" nil nil)
                       ("fo3" "forall ($1:$2) ($3:$4) ($5:$6), $7\n" "forall (3 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/forall_3_args" nil nil)
                       ("fo2" "forall ($1:$2) ($3:$4), $5\n" "forall (2 args)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/forall_2_args" nil nil)
                       ("fo" "forall $1:$2,$3\n" "forall" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/forall" nil nil)
                       ("fold" "fold $1\n" "fold" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fold" nil nil)
                       ("focus" "Focus $1.\n" "Focus" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/focus" nil nil)
                       ("fix" "Fixpoint $1 ($2:$3) {struct ${1:arg}} : $4 :=\n$5.\n" "Fixpoint" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fixpoint" nil nil)
                       ("fsto" "firstorder\n" "firstorder" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/firstorder" nil nil)
                       ("first" "first [ $1 | $2 ]\n" "first" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/first" nil nil)
                       ("field" "field\n" "field" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/field" nil nil)
                       ("false_hyp" "false_hyp ${1:H} ${2:G}\n" "false_hyp" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/false_hyp" nil nil)
                       ("fail" "Fail\n" "Fail" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fail" nil nil)
                       ("fct" "Fact $1 : $2.\n" "Fact" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/fact" nil nil)
                       ("extraction_noinline" "Extraction NoInline $1.\n" "Extraction NoInline" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/extraction_noinline" nil nil)
                       ("extrl" "Extraction Library ${1:id}.\n" "Extraction Library" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/extraction_library" nil nil)
                       ("extrlang" "Extraction Language $1.\n" "Extraction Language" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/extraction_language" nil nil)
                       ("extraction_inline" "Extraction Inline $1.\n" "Extraction Inline" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/extraction_inline" nil nil)
                       ("extr" "Extraction ${1:id}.\n" "Extraction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/extraction" nil nil)
                       ("export" "Export $1.\n" "Export" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/export" nil nil)
                       ("ex" "exists $1\n" "exists" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/exists" nil nil)
                       ("existing_instances" "Existing Instances \n" "Existing Instances" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/existing_instances" nil nil)
                       ("existing_instance" "Existing Instance \n" "Existing Instance" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/existing_instance" nil nil)
                       ("existing_class" "Existing Class \n" "Existing Class" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/existing_class" nil nil)
                       ("exf" "exfalso\n" "exfalso" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/exfalso" nil nil)
                       ("ex" "Example $1:$2 := $3.\n" "Example" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/example" nil nil)
                       ("exa" "exact\n" "exact" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/exact" nil nil)
                       ("eval" "Eval $1.\n" "Eval" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eval" nil nil)
                       ("esp" "esplit\n" "esplit" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/esplit" nil nil)
                       ("er" "erewrite $1\n" "erewrite" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/erewrite" nil nil)
                       ("eqs" "Equations $1:$2 := $3.\n" "Equations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/equations" nil nil)
                       ("eng" "enough ($1: $2).\n{ $3\n}\n" "enough" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/enough" nil nil)
                       ("elt" "elimtype\n" "elimtype" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/elimtype" nil nil)
                       ("e" "elim $1\n" "elim" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/elim" nil nil)
                       ("eleft" "eleft\n" "eleft" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eleft" nil nil)
                       ("eex" "eexists\n" "eexists" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eexists" nil nil)
                       ("edes" "edestruct \n" "edestruct" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/edestruct" nil nil)
                       ("econs" "econstructor\n" "econstructor" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/econstructor" nil nil)
                       ("ea" "eauto\n" "eauto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eauto" nil nil)
                       ("easy" "easy\n" "easy" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/easy" nil nil)
                       ("eas" "eassumption\n" "eassumption" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eassumption" nil nil)
                       ("eap" "eapply $1\n" "eapply" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/eapply" nil nil)
                       ("dind" "double induction $1 $2\n" "double induction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/double_induction" nil nil)
                       ("done" "done\n" "done" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/done" nil nil)
                       ("do" "do ${1:num} ${2:tac}\n" "do" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/do" nil nil)
                       ("discrR" "discrR\n" "discrR" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/discrr" nil nil)
                       ("dis" "discriminate\n" "discriminate" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/discriminate" nil nil)
                       ("deswe" "destruct_with_eqn \n" "destruct_with_eqn" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/destruct_with_eqn" nil nil)
                       ("desall" "destruct_all \n" "destruct_all" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/destruct_all" nil nil)
                       ("des" "destruct \n" "destruct" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/destruct" nil nil)
                       ("deseq" "destr_eq \n" "destr_eq" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/destr_eq" nil nil)
                       ("derive_inversion" "Derive Inversion ${1:id} with $1 Sort $2.\n" "Derive Inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/derive_inversion" nil nil)
                       ("derive_dependent_inversion" "Derive Dependent Inversion ${1:id} with $1 Sort $2.\n" "Derive Dependent Inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/derive_dependent_inversion" nil nil)
                       ("depr" "dependent rewrite -> ${1:id}\n" "dependent rewrite ->" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/dependent_rewrite" nil nil)
                       ("depinvc" "dependent inversion_clear\n" "dependent inversion_clear" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/dependent_inversion_clear" nil nil)
                       ("depinv" "dependent inversion\n" "dependent inversion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/dependent_inversion" nil nil)
                       ("def" "Definition $1:$2 := $3.\n" "Definition" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/definition" nil nil)
                       ("decs" "decompose sum $1\n" "decompose sum" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decompose_sum" nil nil)
                       ("decr" "decompose record $1\n" "decompose record" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decompose_record" nil nil)
                       ("dec" "decompose [$1] $2\n" "decompose" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decompose" nil nil)
                       ("dm" "Declare Module $1 : $2 := $3.\n" "Declare Module : :=" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/declare_module" nil nil)
                       ("declare" "Declare $1.\n" "Declare" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/declare" nil nil)
                       ("decr" "decide_right\n" "decide_right" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decide_right" nil nil)
                       ("decl" "decide_left\n" "decide_left" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decide_left" nil nil)
                       ("deg" "decide equality\n" "decide equality" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decide_equality" nil nil)
                       ("decide" "decide\n" "decide" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/decide" nil nil)
                       ("cutr" "cutrewrite -> $1 = $2\n" "cutrewrite" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cutrewrite" nil nil)
                       ("cut" "cut\n" "cut" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cut" nil nil)
                       ("cor" "Corollary $1 : $2.\nProof.\n$3\nQed.\n" "Corollary" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/corollary" nil nil)
                       ("contr" "contradiction\n" "contradiction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/contradiction" nil nil)
                       ("contr" "contradict\n" "contradict" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/contradict" nil nil)
                       ("context" "Context $1, ($2 : $3).\n" "Context" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/context" nil nil)
                       ("cons" "constructor\n" "constructor" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/constructor" nil nil)
                       ("conj" "Conjecture $1: $2.\n" "Conjecture" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/conjecture" nil nil)
                       ("cong" "congruence\n" "congruence" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/congruence" nil nil)
                       ("con" "congr $1\n" "congr" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/congr" nil nil)
                       ("cmpu" "compute\n" "compute" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/compute" nil nil)
                       ("cmpa" "compare $1 $2\n" "compare" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/compare" nil nil)
                       ("comments" "Comments $1.\n" "Comments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/comments" nil nil)
                       ("coindv" "CoInductive $1 : $2 :=\n|$3 : $4.\n" "CoInductive" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/coinductive" nil nil)
                       ("coind" "coinduction\n" "coinduction" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/coinduction" nil nil)
                       ("cfix" "CoFixpoint $1 ($2:$3) : $4 :=\n$5.\n" "CoFixpoint" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cofixpoint" nil nil)
                       ("cof" "cofix\n" "cofix" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cofix" nil nil)
                       ("coerc" "Coercion ${1:id} : ${2:typ1} >-> ${3:typ2}.\n" "Coercion" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/coercion" nil nil)
                       ("clsc" "Close Scope $1\n" "Close Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/close_scope" nil nil)
                       ("cl" "clearbody\n" "clearbody" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/clearbody" nil nil)
                       ("cldep" "clear dependent\n" "clear dependent" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/clear_dependent" nil nil)
                       ("cl" "clear\n" "clear" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/clear" nil nil)
                       ("class" "Class [ $1 ] := \n$2 : $3;\n$4 : $5.\n" "Class" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/class" nil nil)
                       ("check" "Check\n" "Check" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/check" nil nil)
                       ("chp" "Chapter $1 : $2.\n" "Chapter" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/chapter" nil nil)
                       ("ch" "change \n" "change" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/change" nil nil)
                       ("cd" "Cd $1.\n" "Cd" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cd" nil nil)
                       ("cbv" "cbv beta delta [$1] iota zeta\n" "cbv" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cbv" nil nil)
                       ("cbn" "cbn beta delta [$1] iota zeta\n" "cbn (with flags)" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cbn_with_flags" nil nil)
                       ("c" "cbn\n" "cbn" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/cbn" nil nil)
                       ("cty" "case_type \n" "case_type" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/case_type" nil nil)
                       ("ceq" "case_eq \n" "case_eq" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/case_eq" nil nil)
                       ("case" "case \n" "case" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/case" nil nil)
                       ("canonical_structure" "Canonical Structure $1.\n" "Canonical Structure" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/canonical_structure" nil nil)
                       ("by" "by $1\n" "by" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/by" nil nil)
                       ("bcongr" "bool_congr\n" "bool_congr" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/bool_congr" nil nil)
                       ("bndsc" "Bind Scope ${1:scope} with ${2:type}\n" "Bind Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/bind_scope" nil nil)
                       ("axs" "Axioms $1 , $2: $3\n" "Axioms" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/axioms" nil nil)
                       ("ax" "Axiom $1 : $2\n" "Axiom" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/axiom" nil nil)
                       ("ar" "autorewrite with ${1:db,db...}\n" "autorewrite with" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/autorewrite_with" nil nil)
                       ("a" "auto\n" "auto" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/auto" nil nil)
                       ("as" "assumption\n" "assumption" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/assumption" nil nil)
                       ("assb" "assert ( $1 : $2 ) by $3\n" "assert by" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/assert_by" nil nil)
                       ("argsc" "Arguments Scope ${1:id} [ ${2:_} ]\n" "Arguments Scope" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/arguments_scope" nil nil)
                       ("args" "Arguments ${1:id} : ${2:rule}\n" "Arguments" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/arguments" nil nil)
                       ("ap" "apply \n" "apply" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/apply" nil nil)
                       ("admitted" "Admitted\n" "Admitted" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/admitted" nil nil)
                       ("oblsadmit" "Admit Obligations.\n" "Admit Obligations" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/admit_obligations" nil nil)
                       ("add_setoid" "Add Setoid $1.\n" "Add Setoid" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_setoid" nil nil)
                       ("add_semi_ring" "Add Semi Ring $1.\n" "Add Semi Ring" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_semi_ring" nil nil)
                       ("add_ring" "Add Ring $1.\n" "Add Ring" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_ring" nil nil)
                       ("add_rec_ml_path" "Add Rec ML Path $1.\n" "Add Rec ML Path" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_rec_ml_path" nil nil)
                       ("add_rec_loadpath" "Add Rec LoadPath $1.\n" "Add Rec LoadPath" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_rec_loadpath" nil nil)
                       ("add_printing_let" "Add Printing Let $1.\n" "Add Printing Let" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_printing_let" nil nil)
                       ("add_printing_if" "Add Printing If $1.\n" "Add Printing If" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_printing_if" nil nil)
                       ("add_printing" "Add Printing $1.\n" "Add Printing" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_printing" nil nil)
                       ("add_parametric_relation" "Add Parametric Relation : \n" "Add Parametric Relation" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_parametric_relation" nil nil)
                       ("add_parametric_morphism" "Add Parametric Morphism : \n" "Add Parametric Morphism" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_parametric_morphism" nil nil)
                       ("addmor" "Add Morphism ${1:f} : ${2:id}\n" "Add Morphism" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_morphism" nil nil)
                       ("add_ml_path" "Add ML Path $1.\n" "Add ML Path" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_ml_path" nil nil)
                       ("add_loadpath" "Add LoadPath $1.\n" "Add LoadPath" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_loadpath" nil nil)
                       ("add_field" "Add Field $1.\n" "Add Field" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_field" nil nil)
                       ("add_abstract_semi_ring" "Add Abstract Semi Ring $1.\n" "Add Abstract Semi Ring" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_abstract_semi_ring" nil nil)
                       ("add_abstract_ring" "Add Abstract Ring $1.\n" "Add Abstract Ring" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/add_abstract_ring" nil nil)
                       ("abs" "absurd \n" "absurd" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/absurd" nil nil)
                       ("abstract" "abstract ${1:tac} using ${2:name}.\n" "abstract" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/abstract" nil nil)
                       ("about" "About $1.\n" "About" nil nil nil "/home/hlissner/.config/doom/snippets/coq-mode/about" nil nil)))


;;; Do not edit! File generated at Wed Mar 13 18:35:12 2019
