;;; Compiled snippets and support files for `lua-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'lua-mode
                     '(("while" "while ${1:true} do\n    $0\nend" "while ... do ... end" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/while" nil nil)
                       ("ton" "tonumber($1)\n" "tonumber(...)" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/ton" nil nil)
                       ("=-" "${1:varName} = $1 - ${2:1}" "self-subtraction" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/sub" nil nil)
                       ("sqrt" "math.sqrt($0)\n" "sqrt" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/sqrt" nil nil)
                       ("self:" "function self:${1:methodName}($2)\n    $0\nend\n" "psuedo method declaration" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/self" nil nil)
                       ("req" "require(\"${1:filename}\")\n" "require(...)" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/require" nil nil)
                       ("p" "print(`%`$1)\n" "print" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/print" nil nil)
                       ("pi" "math.pi\n" "pi" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/pi" nil nil)
                       ("open" "io.open(${1:\"${2:filename}\"}, \"${3:r}\")\n" "io.open" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/open" nil nil)
                       ("math.tanh" "math.tanh($0)\n" "math.tanh" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.tanh" nil nil)
                       ("math.tan" "math.tan($0)\n" "math.tan" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.tan" nil nil)
                       ("math.sqrt" "math.sqrt($0)\n" "math.sqrt" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.sqrt" nil nil)
                       ("math.sinh" "math.sinh($0)\n" "math.sinh" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.sinh" nil nil)
                       ("math.sin" "math.sin($0)\n" "math.sin" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.sin" nil nil)
                       ("math.randomseed" "math.randomseed($0)\n" "math.randomseed" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.randomseed" nil nil)
                       ("math.random" "math.random($0)\n" "math.random" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.random" nil nil)
                       ("math.rad" "math.rad($0)\n" "math.rad" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.rad" nil nil)
                       ("math.pow" "math.pow($0)\n" "math.pow" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.pow" nil nil)
                       ("math.pi" "math.pi\n" "math.pi" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.pi" nil nil)
                       ("math.modf" "math.modf($0)\n" "math.modf" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.modf" nil nil)
                       ("math.min" "math.min(${0:x, y, ...})\n" "math.min" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.min" nil nil)
                       ("math.max" "math.max(${0:x, y, ...})\n" "math.max" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.max" nil nil)
                       ("math.log10" "math.log10($0)\n" "math.log10" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.log10" nil nil)
                       ("math.ldexp" "math.ldexp($0)\n" "math.ldexp" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.ldexp" nil nil)
                       ("math.huge" "math.huge($0)\n" "math.huge" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.huge" nil nil)
                       ("math.frexp" "math.frexp($0)\n" "math.frexp" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.frexp" nil nil)
                       ("math.fmod" "math.fmod($0)\n" "math.fmod" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.fmod" nil nil)
                       ("math.floor" "math.floor($0)\n" "math.floor" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.floor" nil nil)
                       ("math.exp" "math.exp($0)\n" "math.exp" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.exp" nil nil)
                       ("math.deg" "math.deg($0)\n" "math.deg" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.deg" nil nil)
                       ("math.cosh" "math.cosh($0)\n" "math.cosh" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.cosh" nil nil)
                       ("math.cos" "math.cos($0)\n" "math.cos" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.cos" nil nil)
                       ("math.ceil" "math.ceil($0)\n" "math.ceil" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.ceil" nil nil)
                       ("math.atan2" "math.atan2(${1:y}, ${2:x})$0\n" "math.atan2" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.atan2" nil nil)
                       ("math.atan" "math.atan($0)\n" "math.atan" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.atan" nil nil)
                       ("math.asin" "math.asin($0)\n" "math.asin" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.asin" nil nil)
                       ("math.acos" "math.acos($0)\n" "math.acos" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.acos" nil nil)
                       ("math.abs" "math.abs($0)\n" "math.abs" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/math.abs" nil nil)
                       ("l" "local $0" "local ..." nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/local" nil nil)
                       ("?" "if ${1:true} then `%`$0 end" "inline if ... then ... end" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/inline-if" nil nil)
                       ("f=" "${1:name} = function($2)\n    ${3:-- code}\nend\n" "? = function(...) ... end" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/inline-function" nil nil)
                       ("if" "if ${1:true} then\n   `%`$0\nend" "if ... then ... end" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/if" nil nil)
                       ("functioni" "function ${1:name}($2) $3 end" "function" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/functioni" nil nil)
                       ("fu" "function ${1:name}($2)\n    ${3:-- code}\nend" "function" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/function" nil nil)
                       ("forline" "f = io.open(${1:\"${2:filename}\"}, \"${3:r}\")\n\nwhile true do\n    line = f:read()\n    if line == nil then break end\n\n    ${0:-- code}\nend\n" "read file line-by-line" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/forline" nil nil)
                       ("fori" "for ${1:i}=${2:1},${3:10} do\n    $0\nend\n" "for loop range" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/fori" nil nil)
                       ("foreach" "for i, ${1:x} in pairs(${2:table}) do\n    $0\nend\n" "for loop range" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/foreach" nil nil)
                       ("for" "for ${1:i}=${2:1},${3:10} do\n    $0\nend\n" "for loop range" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/for" nil nil)
                       ("fi" "function ${1:name}($2) $3 end" "function" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/fi" nil nil)
                       ("elseif" "elseif ${1:true} then\n   `%`$0" "elseif ... then ..." nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/elseif" nil nil)
                       ("cl" "${1:ClassName} = {}\n$1.new = function($2)\n    local self = {}\n\n    ${3:-- code}\n\n    return self\nend" "psuedo class declaration" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/class" nil nil)
                       ("=" "${1:varName} = ${0:value}" "... = ..." nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/assignment" nil nil)
                       ("=+" "${1:varName} = $1 + ${2:1}" "self-addition" nil nil nil "/home/hlissner/.config/doom/snippets/lua-mode/add" nil nil)))


;;; Do not edit! File generated at Wed Mar 13 18:35:12 2019
